language: python
python:
  - 2.7

services:
  - docker

# start the mongodb service
before_install:
  - docker pull mongo
  - docker run -d -p 27017:27017 mongo

#command to install deps
install:
  - "pip install pipenv --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"

script:
  - "pytest"