version: '3'
services:
  mongo_db:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=threat_playbook
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./orl_mongo/:/data/db mongo
  api:
    image: threatplaybook-server:latest
    expose:
      - "5000"
    # ports:
    #   - "5000:5000"
    environment:
      - MONGO_HOST=mongo_db
      - MONGO_PORT=27017
      - MONGO_DB=threat_playbook
      - SUPERUSER_EMAIL=admin@admin.com
      - SUPERUSER_PASS=supersecret
      - JWT_PASS=VGCxqDnhsN6vNQVqmXtrNVVe1AS36ZMQKTq6lYpj0ygHiuWunMOkFi2j17cHSbG-WId9x_yJpeSqy0TTFjs06Q
    links:
      - mongo_db
    depends_on:
      - mongo_db
  frontend:
    image: playbook_new_ui:latest
    expose:
      - "3000"
    # ports:
    #   - "3000:3000"
    environment:
      - VUE_APP_API_URL='http://192.168.0.117:5000/api'
    links:
      - api
    depends_on:
      - api
  gateway:
    build: traefik
    ports:
      - "9000:80"
      - "9090:8080"
    depends_on:
      - api
      - frontend  
