http:
  routers:    
    api:
      rule: "PathPrefix(`/api`)"
      service: api
    frontend:
      rule: "PathPrefix(`/frontend`)"
      service: frontend
  services:    
    frontend:
      loadBalancer:
        servers:
        - url: http://frontend:3000
    api:
      loadBalancer:
        servers:
        - url: http://api:5000